version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dev
          filters:
            branches:
              only: release

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:18.0'
        environment:
          MULE_APP_NAME: demo1-sys-salesforce-api
          MULE_ENV: Sandbox
          MULE_WORKER_TYP: Micro
          MULE_WORKER: 1
          MULE_REGION: us-east-2
          MULE_OSv2: true
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2/repository
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean compile -s settings.xml \
            -Danypoint.user=${ANYPOINT_USER} \
            -Danypoint.password=${ANYPOINT_PASSWORD}
    #  - run:
    #      name: mUnit Test 
    #      command: |
    #        mvn clean test -s settings.xml \
    #        -Danypoint.user=${ANYPOINT_USER} \
    #        -Danypoint.password=${ANYPOINT_PASSWORD}
      - run:
          name: cloudhub deployment
          no_output_timeout: 20m
          command: |            
            mvn clean package deploy -DmuleDeploy -DskipTests \
            -Danypoint.user=${ANYPOINT_USER} \
            -Danypoint.password=${ANYPOINT_PASSWORD} \
            -Danypoint.workers=${MULE_WORKER} \
            -Danypoint.workerType=${MULE_WORKER_TYP} \
            -Danypoint.env=${MULE_ENV} \
            -Danypoint.appName=${MULE_APP_NAME} \
            -Danypoint.region=${MULE_REGION} \
            -Danypoint.osv2=${MULE_OSv2}
            