version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dev
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_APP_NAME: demo-sys-salesforce-api
          MULE_ENV: Sandbox
          MULE_WORKER_TYP: Micro
          MULE_WORKER: 1
          MULE_REGION: us-east-2
          MULE_OSv2: true
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2/repository
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean compile 
      - run:
          name: mUnit Test
          command: |
            mvn clean test 
      - run:
          name: cloudhub deployment
          no_output_timeout: 20m
          command: |            
            mvn clean package deploy -DmuleDeploy  \
            -Danypoint.user=${ANYPOINT_USER} \
            -Danypoint.password=${ANYPOINT_PASSWORD} \
            -Danypoint.workers=${MULE_WORKER} \
            -Danypoint.workerType=${MULE_WORKER_TYP} \
            -Danypoint.env=${MULE_ENV} \
            -Danypoint.appName=${MULE_APP_NAME} \
            -Danypoint.region=${MULE_REGION} \
            -Danypoint.osv2=${MULE_OSv2}
            